#################
###### HUB ######
#################

# kubectl create namespace gke-gateway

# touch gke-gateway-external.yaml
# nano gke-gateway-external.yaml
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: gke-gateway-external
  namespace: gke-gateway
spec:
  gatewayClassName: gke-l7-global-external-managed
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: All

# touch asm-ingressgateway-external-httproute.yaml
# nano asm-ingressgateway-external-httproute.yaml
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: argo-cd
  namespace: gke-gateway
spec:
  parentRefs:
    - kind: Gateway
      name: gke-gateway-external
      namespace: gke-gateway
  rules:
    - backendRefs:
        - kind: Service
          name: argo-cd-argocd-server
          port: 80

# kubectl apply -f gke-gateway-external.yaml

# kubectl apply -f asm-ingressgateway-external-httproute.yaml

########################################################################################################################################################

# helm repo add argo https://argoproj.github.io/argo-helm

# helm install argo-cd argo/argo-cd

# kubectl -n default get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d
# -> {{{{{{ aC56TT7ocT9NdVlM   (zGzOR5h0BhWjQKog)  (rbSqd8aU1seV9WPz)

# kubectl patch svc argo-cd-argocd-server -p '{"spec": {"type": "LoadBalancer"}}'

# kubectl get services (for the ip external)
---
{{{{{{ #https://104.155.58.127     (35.233.29.30)  (35.195.9.33) 
}}}}}}

###############################################################################################
###### SPOKE ##################################################################################
###############################################################################################

# touch secret.yaml
# nano secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubernetes.io/service-account.name: argocd
  name: argocd-token
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd
secrets:
  - name: argocd-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: argocd
    namespace: default

# kubectl apply -f secret.yaml

# kubectl get secrets argocd-token -oyaml
---
{{{{{{ sbox-gkesspk1
}}}}}}

# crt: 
# LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRRnVEMFI1TkdxNC9TV2lXZFpXaGVlakFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRNU1HTTFObUZoTXkweE1EQXhMVFJoTldNdFlUTTJaaTA0WkRRM05UVmpOems1Wm1NdwpJQmNOTWpRd056QXhNRGd5TnpFNVdoZ1BNakExTkRBMk1qUXdPVEkzTVRsYU1DOHhMVEFyQmdOVkJBTVRKRGt3Cll6VTJZV0V6TFRFd01ERXROR0UxWXkxaE16Wm1MVGhrTkRjMU5XTTNPVGxtWXpDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQUltWWtEeElvVFF5NjU0TkJ3RGFRTWgrLy9ldG1SbVRveE5DdHplZgpmN250NE9FTFJLUVpjbTk2QmFSRy9xQ0I0a3U3Y1VWdTFHNzZjKzQ5ZEp1THVFUVAxYVZJRXM5ek5EV3paRU5YCnZPVVVMdkxRdEJOL3J1dEVKS0hLSlhFdldTbzV4Y1IxSS9wMkxCQW5oNGZYaFV4TTkzc05TL1BGejRvMWdEZHkKMnltUTBBSjIrVVlGUnZsSGdrc3NaUzdIaUcydWs2Ymp4RlRmdnBJcWZ2KzRmQ1dRc0UvM2FySU9hSGNlQnp6YgpPYkJPY2dmUC93MGtPYi9BMmVaMERZcHhLWUtSN1N0Q3BoQTNqUGQ2UUV4aWFIdzd0TnYvZkJtYTBNdi9LRFpFCkM0ZnpEV0d1bExSNkpjeFNISG1hUXBnMkxLN2N3aGd5ZVpuclZDM2RuL3NVTGYxdTlnY1I1RmRFQUVGbzl2VlkKSGFUN1VUWVJ0NXVRZDVSanpkNHAzV0hNbjIzMTJQSHpLWldJOGYyMU5JMXVUY0FEekFvRHJSbnVSQlhva2gvRwpMWTJGRDFKUzR3eExLM1lEazRRQ2ExT0dFbk5ONkkwWmFZT1RrWkJvYXhrR2RDcG5mRFFrY3pFdEJzS3Q3dDBOCkM2WEREN2VwR1hHeU5VTWVCazlKMGpUMU9RSURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVU3Nm9NaWhNdGpqT3JjTmtlMm5DUnRWdEFaWk13RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFINFc1OFVPcVJaeG5zOFlKVlZDdFRRc2lFWHJuRmZybnNNbmdLODcyV0k2CkJaTGkrMmJZS2xpekcxMmpIYmN3Q1lJNjBHSEVjam1VSlgvZjJxNVhiZFF0cDA1aENsd2VxOTBUTVdIakt5bEMKdW4wMHU0WXA5cG5xSVBQWDVXb2MzcjZXUnZ3MVp1ZVMvc1VoYmtwSFUwaXRSVGU4TGE5MlBJQXNRVVAxT1hUbApGcGM4OEsrbUdnOGp4MnM4d04xbXRPZ01JK0V1eG5PbWlTQnUxTVh6V3lhMlFoNUNjcHdkaE45RzZvTFJ1cVVoCjFpamVxN3BhTnVNMmRTWFYyRVpJZ0d2N0RjbDkzejJmV0hMOFBLTy9mZjA2OXNKbXRjbDF2UkZtdjRGR1BiZUoKdlNPQWxrQlpEeWVFeEl2N2xuUlBXQ3NxR1JtYW5SV2F6eW1Mc3lCOExsR28rTEFsUkFxeFZ6citCektQNHJ6Qgo0WUwwaFhkcGlZbnZrcnFuRjBTSzc5YzVKZk1aL3U2VFZ5L1E1NlFSNDQxSWVaMFB6Z0pnZFFvVFJMSGFRSHdqClZ6ZkhNK1dqajRzVVRZTy9ZczE5VWpvWXozUmlFbU05eW1WVzEwN3hrRm1aQVg5eXNZMFJEUERIREJpUUMySWQKODRoaGZKN0U1QStvS29weUdUTU9nUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
# token: 
# ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklubHhRM0JQU1dzd01YUXhkMUZvVVhrelgwTmFVMUZGVFhaaGVtNXRiemxCVFVGTGNXMTVaVlpxTWswaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbUZ5WjI5alpDMTBiMnRsYmlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKaGNtZHZZMlFpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1MWFXUWlPaUkwTVRsaE5ETTVNaTAxT1dNNExUUTROek10T1dNM05DMWhZamRoWWpaa01HWTRNelVpTENKemRXSWlPaUp6ZVhOMFpXMDZjMlZ5ZG1salpXRmpZMjkxYm5RNlpHVm1ZWFZzZERwaGNtZHZZMlFpZlEuZ2xyZUYzdXFpbWhWVjA4ZENJY2dyaG5DVnhfQmVYcWxQLUUzWHJ5Y3RvcE84RnRUbEFTSk81SmM0eE5sbnR6MDY5aDRJT0M3dDZsSGhlOWVDVnVrbXp1TVlBUXNWZEdpeE5ockF2X1FUR052aWpNbWE5dkJwUFROOFJZZkxOVzFsaE5pTFAyRFRYbTFKM1FuMXJIaDV4Rk45bGFUa1ItM3Rwd2VnZWpoa1BfSWVhMW14S0l5UEdMUkI1Uk5scDFVUVI4M0FPajRtVlVGU3lna1hlYVVBa2NNckRzY0lSTFdrdzlFYjJqdXFVZF9aQjlPam9xcDJxN1VkRmwxNFhFM0FTaWNuTXp6TmZOam1HbVJMOVRjcG54MXhORmhaTi1ULWZsaVFwZ0VfdEpOTlFKXzI0bTVFRkNJb3MzVXZQVDZQTEo1aUZkVlVpc3ZwVnNiY2dLZWpn

# echo "ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNklubHhRM0JQU1dzd01YUXhkMUZvVVhrelgwTmFVMUZGVFhaaGVtNXRiemxCVFVGTGNXMTVaVlpxTWswaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbUZ5WjI5alpDMTBiMnRsYmlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKaGNtZHZZMlFpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1MWFXUWlPaUkwTVRsaE5ETTVNaTAxT1dNNExUUTROek10T1dNM05DMWhZamRoWWpaa01HWTRNelVpTENKemRXSWlPaUp6ZVhOMFpXMDZjMlZ5ZG1salpXRmpZMjkxYm5RNlpHVm1ZWFZzZERwaGNtZHZZMlFpZlEuZ2xyZUYzdXFpbWhWVjA4ZENJY2dyaG5DVnhfQmVYcWxQLUUzWHJ5Y3RvcE84RnRUbEFTSk81SmM0eE5sbnR6MDY5aDRJT0M3dDZsSGhlOWVDVnVrbXp1TVlBUXNWZEdpeE5ockF2X1FUR052aWpNbWE5dkJwUFROOFJZZkxOVzFsaE5pTFAyRFRYbTFKM1FuMXJIaDV4Rk45bGFUa1ItM3Rwd2VnZWpoa1BfSWVhMW14S0l5UEdMUkI1Uk5scDFVUVI4M0FPajRtVlVGU3lna1hlYVVBa2NNckRzY0lSTFdrdzlFYjJqdXFVZF9aQjlPam9xcDJxN1VkRmwxNFhFM0FTaWNuTXp6TmZOam1HbVJMOVRjcG54MXhORmhaTi1ULWZsaVFwZ0VfdEpOTlFKXzI0bTVFRkNJb3MzVXZQVDZQTEo1aUZkVlVpc3ZwVnNiY2dLZWpn" | base64 -d
# -> eyJhbGciOiJSUzI1NiIsImtpZCI6InlxQ3BPSWswMXQxd1FoUXkzX0NaU1FFTXZhem5tbzlBTUFLcW15ZVZqMk0ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFyZ29jZC10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhcmdvY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiI0MTlhNDM5Mi01OWM4LTQ4NzMtOWM3NC1hYjdhYjZkMGY4MzUiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDphcmdvY2QifQ.glreF3uqimhVV08dCIcgrhnCVx_BeXqlP-E3XryctopO8FtTlASJO5Jc4xNlntz069h4IOC7t6lHhe9eCVukmzuMYAQsVdGixNhrAv_QTGNvijMma9vBpPTN8RYfLNW1lhNiLP2DTXm1J3Qn1rHh5xFN9laTkR-3tpwegejhkP_Iea1mxKIyPGLRB5RNlp1UQR83AOj4mVUFSygkXeaUAkcMrDscIRLWkw9Eb2juqUd_ZB9Ojoqp2q7UdFl14XE3ASicnMzzNfNjmGmRL9Tcpnx1xNFhZN-T-fliQpgE_tJNNQJ_24m5EFCIos3UvPT6PLJ5iFdVUisvpVsbcgKejg

---
{{{{{{ sbox-gkesspk2
}}}}}}
# crt: 
# LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRRVNFREYvcDRjeFhxb3pPeGtMZC8rREFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRME5qVTJPR1V5T0MxaU9HUm1MVFF3WmpFdE9HSXlZeTAyTnpsbE5HTmtPRFZrTWpndwpJQmNOTWpRd056QXpNRGt3TnpNMldoZ1BNakExTkRBMk1qWXhNREEzTXpaYU1DOHhMVEFyQmdOVkJBTVRKRFEyCk5UWTRaVEk0TFdJNFpHWXROREJtTVMwNFlqSmpMVFkzT1dVMFkyUTROV1F5T0RDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQUx3Zzl3QTh4bFdRMkhXVFVZS1pmWDFxNWNnbm5KZmEwV3hLNGRNVwpDRkUyUVR0cFY2T25GcFQ4Mnpma1ZXbGdWTFBCTmdsOGM1aXpHVzhycEdTYmhIam12TXB2L1VvZWFxZS9iU1pqCmRxVnNDUnNiamhjWTR5bHQwZmgwZmNVOHk1SHlFNmJjN0tmZDZDOW5GeXpTcjU4Z2UxK3NhV1lWbGsxUXg4NmsKMWVxNzlLbzJLd2hDL0YvZWo3dmJoOEZhaS8yWFowVGFKODd0RVRBMHN6WEtpcEtYZGhKTmNwUGJBNnFuR1FZdgpHUmZybXNmcDZPMUJFTFJUcE84Nzh6amRZLyt0ZzMyVFh0TUJFZ0cyK215aDhGRmpwV0tsK1kraVpOYUw1OHIyCnJIT1RHQmRSb1lVS1lQOW81eENrM2V0ekxlakJPZFk0MUlJeUNqbCtVd09TUmdXNjAzSU1rb0paM1IxL3dzVTQKSUhJQld2dXdMOUVEWDRvOWIvVXJZT0lMU0xHVVl3Q2k3dkY4SGtXMEQ4UFp5a0VOcnJlNkJwaEI3eDJ6a1RHdQo0ZUpNbG9nRGU5Ykl3S1MwMkNycFcvUzFDaDkxdVhVSE5aQ2tkRGZHcG15RlNSa2IrTysxaUN0ajhpQkhBS1ByCm15NjN1b0xoYXEyc01OTGdHVjJnWGdoTyt3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVoRldpdzZEN25FNnB0Q2xKd3dyS2NxVUNTK1V3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFKeTFqRzdaM3J1U3hqbjNrcDZnM2h1SnppY2kwbHo2K3VpRytBM0xNSmF6Cnd2TnUwL1hWQWl2cXBXY2FzY1hJTXA3Yy9yTjNFc3lvYmFCWjRJK2QydllncXFSUGkwclFUNXd1cmttSTRHQUEKemltdDdBTFBUL3VYUi9XRHBYcTdFbVgwUmdJSlhhczNCZldlajNNbFh0dFFWVEIvODM5WkdSTTVmei81ZGVEawpvU3NnNzRwRFJjT2NxaGNFaDBZNGEvMEpUdHEyQ3NySXVhTmZaNlJDZWRVNTIzZW5BZUJRMU0yVms1eUx4QndGCk1PUk1hcUl0RURLWGc5VGE3ZzVMUWh2bnF3ZFNtamlreEZpZ2MxZkIyNGJmTStWUjdwMVlhajZ1a3g5QWF3aVoKMXozSUJrVWxjRmhTc3hLTlhycnJSVHp1dDIvYVdaTkk5VkNiQWhaR3IzZ29WV1NVSmNEOHV3SERWdExxYmxWdApGK1F6cUpLRFhnaXArM0tWY25YbHExdVRYTGpVNFNEenNOTTJoVWF2SmF1QnVRMlJYODVjNDhFbUFoMHQzUXZUClp1S1ZoMWl4blBRZ3MycDBSOHRXQnlwWlJZOWhVWnlhVkc4SU9jRjBUa2E3Rm1FT2NUZGt1WFVPSFlHTkluSXcKTzA4a1JadjVPdG1xOG1IcGhyTzhudz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
# token: 
# ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltazJPVmRvVGpKcmFUVmlTa3A1YlVjMWRXSXdhelJMVEdSdmVrdzNNMFV3TW0xdGVYRkpiWHBmWTAwaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbUZ5WjI5alpDMTBiMnRsYmlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKaGNtZHZZMlFpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1MWFXUWlPaUptTjJNeE1qbG1OeTFqWldNMUxUUTBPVEF0WWpkaU15MHhOemc0T0RKa05tSXdZallpTENKemRXSWlPaUp6ZVhOMFpXMDZjMlZ5ZG1salpXRmpZMjkxYm5RNlpHVm1ZWFZzZERwaGNtZHZZMlFpZlEuWkRteFlxalhPamoyZVotdmYxMU96Q0ZBMDBKRDJjbVF0SzJ2WkRYWDNZU2puTTFLQUxPX0M2UjFad3ZVWG9ERkdIUW15ajlBbWRkQUpOckdkZzRvajBtLXowbGE3cXRsUVZmZk1QREs0S0RZV1VvTWlaWDdvOTlDcW1pUldMbkZTYzdZRFJJcm9FWnBsM0dEREtpbC0xY0ZtckF3SnpVVkZZWFNMeGhJOV9iWUQwNU1QTVY1dFpyYWZmZmRGdXYydDJ5UFBXeEFBY3ptWW5xcFlmbTJWblZOcWxWQUgzV0hBMmNja3dZbFZpMFBpajhmdi1keHhTdTB3Wm5aa2EzOU9uY05WTzBEYVJiVXJXSGNUOHQ4S1dHeDZrbGxHejhGcTlSbUdpUkh1dW82OTlsVnlFdXgwVjkxNExUakVLY3ZLNDFoc3NEcjRNeF9aU1V1QV9IdWdB

# echo "ZXlKaGJHY2lPaUpTVXpJMU5pSXNJbXRwWkNJNkltazJPVmRvVGpKcmFUVmlTa3A1YlVjMWRXSXdhelJMVEdSdmVrdzNNMFV3TW0xdGVYRkpiWHBmWTAwaWZRLmV5SnBjM01pT2lKcmRXSmxjbTVsZEdWekwzTmxjblpwWTJWaFkyTnZkVzUwSWl3aWEzVmlaWEp1WlhSbGN5NXBieTl6WlhKMmFXTmxZV05qYjNWdWRDOXVZVzFsYzNCaFkyVWlPaUprWldaaGRXeDBJaXdpYTNWaVpYSnVaWFJsY3k1cGJ5OXpaWEoyYVdObFlXTmpiM1Z1ZEM5elpXTnlaWFF1Ym1GdFpTSTZJbUZ5WjI5alpDMTBiMnRsYmlJc0ltdDFZbVZ5Ym1WMFpYTXVhVzh2YzJWeWRtbGpaV0ZqWTI5MWJuUXZjMlZ5ZG1salpTMWhZMk52ZFc1MExtNWhiV1VpT2lKaGNtZHZZMlFpTENKcmRXSmxjbTVsZEdWekxtbHZMM05sY25acFkyVmhZMk52ZFc1MEwzTmxjblpwWTJVdFlXTmpiM1Z1ZEM1MWFXUWlPaUptTjJNeE1qbG1OeTFqWldNMUxUUTBPVEF0WWpkaU15MHhOemc0T0RKa05tSXdZallpTENKemRXSWlPaUp6ZVhOMFpXMDZjMlZ5ZG1salpXRmpZMjkxYm5RNlpHVm1ZWFZzZERwaGNtZHZZMlFpZlEuWkRteFlxalhPamoyZVotdmYxMU96Q0ZBMDBKRDJjbVF0SzJ2WkRYWDNZU2puTTFLQUxPX0M2UjFad3ZVWG9ERkdIUW15ajlBbWRkQUpOckdkZzRvajBtLXowbGE3cXRsUVZmZk1QREs0S0RZV1VvTWlaWDdvOTlDcW1pUldMbkZTYzdZRFJJcm9FWnBsM0dEREtpbC0xY0ZtckF3SnpVVkZZWFNMeGhJOV9iWUQwNU1QTVY1dFpyYWZmZmRGdXYydDJ5UFBXeEFBY3ptWW5xcFlmbTJWblZOcWxWQUgzV0hBMmNja3dZbFZpMFBpajhmdi1keHhTdTB3Wm5aa2EzOU9uY05WTzBEYVJiVXJXSGNUOHQ4S1dHeDZrbGxHejhGcTlSbUdpUkh1dW82OTlsVnlFdXgwVjkxNExUakVLY3ZLNDFoc3NEcjRNeF9aU1V1QV9IdWdB" | base64 -d
# -> eyJhbGciOiJSUzI1NiIsImtpZCI6Imk2OVdoTjJraTViSkp5bUc1dWIwazRLTGRvekw3M0UwMm1teXFJbXpfY00ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFyZ29jZC10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhcmdvY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJmN2MxMjlmNy1jZWM1LTQ0OTAtYjdiMy0xNzg4ODJkNmIwYjYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDphcmdvY2QifQ.ZDmxYqjXOjj2eZ-vf11OzCFA00JD2cmQtK2vZDXX3YSjnM1KALO_C6R1ZwvUXoDFGHQmyj9AmddAJNrGdg4oj0m-z0la7qtlQVffMPDK4KDYWUoMiZX7o99CqmiRWLnFSc7YDRIroEZpl3GDDKil-1cFmrAwJzUVFYXSLxhI9_bYD05MPMV5tZrafffdFuv2t2yPPWxAAczmYnqpYfm2VnVNqlVAH3WHA2cckwYlVi0Pij8fv-dxxSu0wZnZka39OncNVO0DaRbUrWHcT8t8KWGx6kllGz8Fq9RmGiRHuuo699lVyEux0V914LTjEKcvK41hssDr4Mx_ZSUuA_HugA


#############################################################################################
###### HUB ##################################################################################
#############################################################################################
---
{{{{{{ Get control plane ip in the state file (search by Control plane address range) }}}}}}

# touch secret_sploke.yaml
# nano secret_sploke.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: sbox-gkesspk-cluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  config: >
    {
      "bearerToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6Imk2OVdoTjJraTViSkp5bUc1dWIwazRLTGRvekw3M0UwMm1teXFJbXpfY00ifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImFyZ29jZC10b2tlbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhcmdvY2QiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiJmN2MxMjlmNy1jZWM1LTQ0OTAtYjdiMy0xNzg4ODJkNmIwYjYiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6ZGVmYXVsdDphcmdvY2QifQ.ZDmxYqjXOjj2eZ-vf11OzCFA00JD2cmQtK2vZDXX3YSjnM1KALO_C6R1ZwvUXoDFGHQmyj9AmddAJNrGdg4oj0m-z0la7qtlQVffMPDK4KDYWUoMiZX7o99CqmiRWLnFSc7YDRIroEZpl3GDDKil-1cFmrAwJzUVFYXSLxhI9_bYD05MPMV5tZrafffdFuv2t2yPPWxAAczmYnqpYfm2VnVNqlVAH3WHA2cckwYlVi0Pij8fv-dxxSu0wZnZka39OncNVO0DaRbUrWHcT8t8KWGx6kllGz8Fq9RmGiRHuuo699lVyEux0V914LTjEKcvK41hssDr4Mx_ZSUuA_HugA",
      "tlsClientConfig": {
        "insecure": false,
        "caData": "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRRVNFREYvcDRjeFhxb3pPeGtMZC8rREFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRME5qVTJPR1V5T0MxaU9HUm1MVFF3WmpFdE9HSXlZeTAyTnpsbE5HTmtPRFZrTWpndwpJQmNOTWpRd056QXpNRGt3TnpNMldoZ1BNakExTkRBMk1qWXhNREEzTXpaYU1DOHhMVEFyQmdOVkJBTVRKRFEyCk5UWTRaVEk0TFdJNFpHWXROREJtTVMwNFlqSmpMVFkzT1dVMFkyUTROV1F5T0RDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQUx3Zzl3QTh4bFdRMkhXVFVZS1pmWDFxNWNnbm5KZmEwV3hLNGRNVwpDRkUyUVR0cFY2T25GcFQ4Mnpma1ZXbGdWTFBCTmdsOGM1aXpHVzhycEdTYmhIam12TXB2L1VvZWFxZS9iU1pqCmRxVnNDUnNiamhjWTR5bHQwZmgwZmNVOHk1SHlFNmJjN0tmZDZDOW5GeXpTcjU4Z2UxK3NhV1lWbGsxUXg4NmsKMWVxNzlLbzJLd2hDL0YvZWo3dmJoOEZhaS8yWFowVGFKODd0RVRBMHN6WEtpcEtYZGhKTmNwUGJBNnFuR1FZdgpHUmZybXNmcDZPMUJFTFJUcE84Nzh6amRZLyt0ZzMyVFh0TUJFZ0cyK215aDhGRmpwV0tsK1kraVpOYUw1OHIyCnJIT1RHQmRSb1lVS1lQOW81eENrM2V0ekxlakJPZFk0MUlJeUNqbCtVd09TUmdXNjAzSU1rb0paM1IxL3dzVTQKSUhJQld2dXdMOUVEWDRvOWIvVXJZT0lMU0xHVVl3Q2k3dkY4SGtXMEQ4UFp5a0VOcnJlNkJwaEI3eDJ6a1RHdQo0ZUpNbG9nRGU5Ykl3S1MwMkNycFcvUzFDaDkxdVhVSE5aQ2tkRGZHcG15RlNSa2IrTysxaUN0ajhpQkhBS1ByCm15NjN1b0xoYXEyc01OTGdHVjJnWGdoTyt3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVVoRldpdzZEN25FNnB0Q2xKd3dyS2NxVUNTK1V3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFKeTFqRzdaM3J1U3hqbjNrcDZnM2h1SnppY2kwbHo2K3VpRytBM0xNSmF6Cnd2TnUwL1hWQWl2cXBXY2FzY1hJTXA3Yy9yTjNFc3lvYmFCWjRJK2QydllncXFSUGkwclFUNXd1cmttSTRHQUEKemltdDdBTFBUL3VYUi9XRHBYcTdFbVgwUmdJSlhhczNCZldlajNNbFh0dFFWVEIvODM5WkdSTTVmei81ZGVEawpvU3NnNzRwRFJjT2NxaGNFaDBZNGEvMEpUdHEyQ3NySXVhTmZaNlJDZWRVNTIzZW5BZUJRMU0yVms1eUx4QndGCk1PUk1hcUl0RURLWGc5VGE3ZzVMUWh2bnF3ZFNtamlreEZpZ2MxZkIyNGJmTStWUjdwMVlhajZ1a3g5QWF3aVoKMXozSUJrVWxjRmhTc3hLTlhycnJSVHp1dDIvYVdaTkk5VkNiQWhaR3IzZ29WV1NVSmNEOHV3SERWdExxYmxWdApGK1F6cUpLRFhnaXArM0tWY25YbHExdVRYTGpVNFNEenNOTTJoVWF2SmF1QnVRMlJYODVjNDhFbUFoMHQzUXZUClp1S1ZoMWl4blBRZ3MycDBSOHRXQnlwWlJZOWhVWnlhVkc4SU9jRjBUa2E3Rm1FT2NUZGt1WFVPSFlHTkluSXcKTzA4a1JadjVPdG1xOG1IcGhyTzhudz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
      }
    }
  name: sbox-gkesspk
  server: https://192.168.3.2  https://192.168.2.2
type: Opaque

# kubectl apply -f secret_spoke.yaml

# --kubectl create namespace infra

# touch AppProject.yaml
# nano AppProject.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra-dev-stage
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: infra
      server: 192.168.2.0/28
  sourceRepos:
    - https://github.com/rferreim/AppProjectTest.git
    - https://helm.releases.hashicorp.com

# touch applicationSet.yaml
# nano applicationSet.yaml
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
spec:
  goTemplate: true
  goTemplateOptions:
    - missingkey=error
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster

# kubectl apply -f AppProject.yaml

# kubectl apply -f applicationSet.yaml

# .argocd.json
# values.nprod.yaml
# values.nprod.yaml
---
{{{{{{ helm delete argo-cd }}}}}}